version: '3.5'
services:
  mysql:
    image: mysql:5.7
    restart: always
    expose:
      - "3306"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: snello
      MYSQL_DATABASE: snello
      MYSQL_USER: snello
      MYSQL_PASSWORD: snello
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --max-connections=1000, --wait-timeout=300, --interactive-timeout=300]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    logging:
      driver: none
    depends_on:
      - mysql
    links:
      - mysql:db
    expose:
      - "80"
    ports:
      - "9999:80"
  snello-api:
    image: snello/snello-api:latest
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ./webroot:/home/snello/webroot
    environment:
      WEBROOT: /webroot
      JDBC_PASSWORD: snello
      JDBC_USERNAME: snello
      JDBC_URL: 'jdbc:mysql://mysql:3306/snello?verifyServerCertificate=false&useSSL=true'
      JDBC_DRIVER: com.mysql.jdbc.Driver
      JDBC_VALIDATION_QUERY: 'select 1'
  snello-admin:
    image: snello/snello-admin:latest
    ports:
      - "8081:80"
  frontend:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - snello-api
      - snello-admin

